# Site settings
name: Malena Bashar
title: Malena Bashar | Software Engineer
description: I automate technical debt, ensure our distributed fleet is running, and write too many config files
url: https://malenabashar.github.io/
baseurl: ''
email: malenabashar.mail@gmail.com
cover: https://NaeemH.github.io/img/og2.png
logo: https://NaeemH.github.io/images/favicon.ico
resume: https://docs.google.com/document/d/15F0iTz2M-Q8R6sdh8eNi4htlfKTLCixtSPxbXzhvf2Q/edit?usp=sharing
social:
  - title: resume
    url: https://docs.google.com/document/d/15F0iTz2M-Q8R6sdh8eNi4htlfKTLCixtSPxbXzhvf2Q/edit?usp=sharing
#  - title: twitter
#    url: https://twitter.com/Nakjeem
#  - title: instagram
#    url: https://instagram.com/hackernemo
#  - title: codepen
#    url: http://codepen.io/NaeemH
  - title: github
    url: https://github.com/malenabashar
  - title: linkedin
    url: https://www.linkedin.com/in/malena-bashar
  - title: email
    url: mailto:malenabashar.mail@gmail.com

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
